### PR TITLE
[FIX] content-script / background

### PR DESCRIPTION
**Pull request by rrfaria**
- fix Content script and background script is not been loaded

### CODE REVIEW

**Comment by SubZtep** [comment]
Thanks for this PR, solved my issue. :pray:

Until the new release here is a quick fix in `vue.config.js`:
```js
module.exports = {
  // ...
  configureWebpack: config => {
    if (process.env.NODE_ENV !== "production") {
      config.optimization.splitChunks.cacheGroups.vendors.chunks = () => false
      config.optimization.splitChunks.cacheGroups.common.chunks = () => false
    }
  }
}
```

**Comment by franciscolourenco** [comment]
Can you describe the problem this is supposed to fix? thanks.

**Comment by eamonnmg** [comment]
This fixed my issue too. Before background.js would not run for some reason.

Not sure why it works (or didn't work in first place) though 😅

**Comment by rrfaria** [comment]
My PR didn't work properly has some issues to be fixed , but the code need to be better analysed

**Comment by adambullmer** [comment]
Figured out the root cause as to why this was necessary. Looks like later versions of vue-cli-service would add the optimizations into development builds. A release has been pushed on `0.23.1` to resolve this.

**Pull request closed without merging**
