### PR TITLE
Support custom artifact filenames

### PR DESCRIPTION
**Pull request by siphomateke**
Useful for naming builds for different browsers.

### CODE REVIEW

**Comment by kernel-picnic** [comment]
Very helpful for multiple builds 👍

**Comment by adambullmer** [comment]
:tada: released in 0.25.2

**Comment by kernel-picnic** [comment]
@adambullmer thanks!

**Comment by Hinara** [comment]
@adambullmer This is not included in 0.25.2 hope for a new release with this PR in.

**Pull request merged**
